# Generated by Django 5.2.4 on 2025-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
