# Generated by Django 5.2.4 on 2025-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
